# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@dd3c524b3f9f0f21d3c19962ba52ba58d835bfda
    with:
      extension-name: minimal-grey-firefox
      release-version: ${{ github.ref_name }}
    secrets: inherit
