# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@2fde90ca793b21b68edc62e13266f44b08018da0
    with:
      extension-name: minimal-grey-firefox
      release-version: ${{ github.ref_name }}
    secrets: inherit
