# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@205de59141634aacef23ca5df55f67f4657bf913
    with:
      extension-name: minimal-grey-firefox
      release-version: ${{ github.ref_name }}
    secrets: inherit
