# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@a2eea2d010a33d3ef52ea55645d84ca88a373a38
    with:
      extension-name: minimal-grey-firefox
      release-version: ${{ github.ref_name }}
    secrets: inherit
