# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@99d22090f97a855f32af8a5f56523a6a88bb2857
    with:
      extension-name: minimal-grey-firefox
      release-version: ${{ github.ref_name }}
    secrets: inherit
